### ISSUE TITLE
Error when using part of the URL instead of Page Title

### ISSUE THREAD

**Issue by avorio** [goldsmith/Wikipedia#124]
Take for example this Wikipedia page:

https://en.wikipedia.org/wiki/Avant-dernières_pensées

When I run:

```python
wikipedia.summary(title="Avant-dernières_pensées")
```

I get the following error:

```
PageError
[...]/python3.4/site-packages/wikipedia/wikipedia.py in __load, line 345
Page id "avant dernières pensées" does not match any pages. Try another id!
```

However, when I replace `_` with spaces, it works. Example:

```python
wikipedia.summary(title="Avant-dernières_pensées".replace('_', ' '))
```

```
'The Avant-dernières pensées (Penultimate Thoughts) is a 1915 piano composition by Erik Satie. The last of his humoristic piano suites of the 1910s, it was premiered by the composer at the Galerie Thomas in Paris on May 30, 1916, and published that same year. A typical performance lasts 3-4 minutes.'
```

I'd like to use the page title as it appears in the URL **as well as** the nicely-formatted version.

Is that the intended use in the library?

**Comment by abspoel** [comment]
Try

    wikipedia.summary("Avant-dernières_pensées", auto_suggest=False)

if you know the proper URL.

**Comment by avorio** [comment]
That works, @abspoel! Many thanks for your suggestion.
