### ISSUE TITLE
Content returning empty string

### ISSUE THREAD

**Issue by mike-a-yen** [goldsmith/Wikipedia#150]
<img width="328" alt="screen shot 2017-05-12 at 8 49 14 am" src="https://cloud.githubusercontent.com/assets/12302641/26010615/815b0740-3702-11e7-9a87-64420082d09a.png">

**Comment by mike-a-yen** [comment]
Looks like wiki api is not responding.

**Comment by Hallicopter** [comment]
Same as issue #149

**Comment by mike-a-yen** [comment]
It looks like the wikipedia api is accepting the `prop=extracts` param but will always return an empty string.

**Comment by mike-a-yen** [comment]
Looks to be working again now.
