### ISSUE TITLE
Update PyPi code

### ISSUE THREAD

**Issue by davebulaval** [goldsmith/Wikipedia#209]
The code on PyPi is outdated.

https://pypi.org/project/wikipedia/

Please updated it.

**Comment by barrust** [comment]
This module is fairly outdated and isn't actively maintained. To use it you will either need to build from source or use some of the other forks/rewrites of the library. I maintain one called [pymediawiki](https://github.com/barrust/mediawiki) that is up to date on pypi. I do know that there  are others that do similar things. It all depends on what you are looking for. 

Good luck!
