### ISSUE TITLE
"(" or ")" in string while using wikipedia.page(...)

### ISSUE THREAD

**Issue by Harshal96** [goldsmith/Wikipedia#214]
The code:

`wikipedia.page("Oil_pump_(internal_combustion_engine)").content` 

gives me an error:

`wikipedia.exceptions.PageError: Page id "oil_pump_ internal combustion engine" does not match any pages. Try another id!`

But when I remove the brackets from the search string, it works as expected. As I can also see, in the error message, the brackets have disappeared.

In reality, the URL is: https://en.wikipedia.org/wiki/Oil_pump_(internal_combustion_engine)

**Comment by barrust** [comment]
The page search is based on the page title, not the URL. Try using

``` python
wikipedia.page("Oil pump (internal combustion engine)") 
```

If you are looking for a maintained library, I would recommend [pymediawiki](https://github.com/barrust/mediawiki) (full disclosure, I maintain pymediawiki)
