### ISSUE TITLE
Want to extract the below information that shared in the page

### ISSUE THREAD

**Issue by bpkapkar** [goldsmith/Wikipedia#229]
![Licensing](https://user-images.githubusercontent.com/49440262/81808133-e3c2eb00-953c-11ea-8eb8-caef73855241.JPG)

How can we extract the information  that is shown in the image , mainly I want to extract licensing information (open source/ Freeware/ Licensed)

Paradigm | Multi-paradigm: functional, imperative, object-oriented, structured, reflective
-- | --
Guido van Rossum
Python Software Foundation
1990; 30 years ago[1]
 
3.8.2 / 24 February 2020; 2 months ago[2]
3.9.0a6 / 28 April 2020; 15 days ago[3]
Duck, dynamic, gradual(since 3.5)[4]
Linux, macOS, WindowsVista (and newer) and more
Python Software Foundation License
.py, .pyi, .pyc, .pyd, .pyo (prior to 3.5),[5] .pyw, .pyz (since 3.5)[6]
www.python.org

**Comment by Muhimen123** [comment]
You want the information of that chart like table? Currently, this module doesn't support this kind of information extracting. However, you can use simple web scraping to gather inforamation like this.
