### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by TheBugYouCantFix** [goldsmith/Wikipedia#240]
I write the telegram bot using this module and it shows the following mistake:

wikipedia.exceptions.WikipediaException: An unknown error occured: "Search request is longer than the maximum allowed length. (1825 > 300)". Please report it on GitHub!

**Comment by alphapapa** [comment]
You have reported this issue twice on this repo, here and at https://github.com/goldsmith/Wikipedia/issues/248.  Please close this issue.
