### ISSUE TITLE
Colombia/Columbia disambiguation error

### ISSUE THREAD

**Issue by StrawnSC** [goldsmith/Wikipedia#245]
When I try to get a page by the title "Colombia": `wikipedia.page("colombia")`, I get a disambiguation error for "Columbia" -- note the different spelling. 
There are separate disambiguation pages for "Colombia" and "Columbia," and there's also a wikipedia page for just "Colombia," so I'm not sure why the disambiguation would be for "Columbia."

**Comment by JAcamp1** [comment]
The closest page relating to that search is a disambiguation page that Wikipedia places a priority on over normal pages as they clear up the confusion between articles. Try to catch the exception. Its type is wikipedia.exceptions.DisambiguationError.
