### ISSUE TITLE
BMW issue 

### ISSUE THREAD

**Issue by TheBugYouCantFix** [goldsmith/Wikipedia#247]
when I look for summary, page, search, or any other function + BMW it gives me the following output:

wikipedia.exceptions.DisambiguationError: "BM" may refer to: 
BM (album)
B minor
Bachelor of Music
Beautiful music
Black metal
Big Matthew
Bashir Mirza
Brick and mortar
Birmingham Midshires
Bolinder-Munktell
Bolliger & Mabillard
Boston and Maine Corporation
British Midland International
BMI Regional
Bachelor of Medicine
glucose meter
Bowel movement
Bacterial Meningitis
.bm
Builder's Old Measurement
Bambara language
Bandmaster
Boatswain's mate (United States Navy)
Boatswain's mate (United States Coast Guard)
Bravery Medal (Australia)
Martin BM
Bermuda
.bm
Birch Mountains kimberlite field
Burma
Bukit Merah
British Museum
British Movement

And yes, I am sure I typed "BMW", not  just "BM"

It would be nice if you could fix this issue 

Thanks

**Comment by alphapapa** [comment]
Please retitle this issue appropriately.  The issue you describe has nothing to do with BMW.

**Comment by alphapapa** [comment]
See https://github.com/goldsmith/Wikipedia/issues/227

**Comment by apetridis** [comment]
try excepting this error like this 
    try:
        page = wikipedia.WikipediaPage(title)
    except wikipedia.exceptions.DisambiguationError as e:
        page = wikipedia.WikipediaPage(e.options[0])
