### ISSUE TITLE
Probably the most hilarious issue

### ISSUE THREAD

**Issue by TheBugYouCantFix** [goldsmith/Wikipedia#249]
When I look for USSR it gives me the info about the US, lmao. Would be really great if you could fix it

**Comment by alphapapa** [comment]
Would be really great if you showed a reproducible example with code.

**Comment by alphapapa** [comment]
See https://github.com/goldsmith/Wikipedia/issues/227.  This also seems to duplicate the other issue you filed about this, #247, so you should close this issue.
