### ISSUE TITLE
It does not spot all disambiguation pages

### ISSUE THREAD

**Issue by ghost** [goldsmith/Wikipedia#252]
I just tried "Arla" keyword and it is refered as a disambiguation page see https://en.wikipedia.org/wiki/Arla

```
import wikipedia
import random
ee = None
try:
    p = wikipedia.summary("Arla")
except wikipedia.DisambiguationError as e:
    ee = e
    s = random.choice(e.options)
    p = wikipedia.page(s)
```

How to deal with this, I have a lot of keywords that I want to retrieve only articles that fall in a specific category (topic "food and beverages)

Many thanks !

**Comment by KairaNithin** [comment]
try **wikipedia.summary("Arla",auto_suggest=False)** as suggested by @wlerin. But this do not work with few words.
