### ISSUE TITLE
ModuleNotFoundError: No module named 'wiki'

### ISSUE THREAD

**Issue by edgui-appolonicorreia** [goldsmith/Wikipedia#263]
Hello guys, I'm trying to get some [SNPedia](https://www.snpedia.com/index.php/SNPedia) data. The [SNPedia API's](https://www.snpedia.com/index.php/Bulk) documentation page says:

![image](https://user-images.githubusercontent.com/37029029/104380179-61def380-5509-11eb-950a-289894ecc6bf.png)

So, I started a **Google Colab** and a **Jupyter Notbook** on my local machine and I got this error in both cases:

![image](https://user-images.githubusercontent.com/37029029/104381107-cb133680-550a-11eb-9106-0a21a8702d43.png)
![image](https://user-images.githubusercontent.com/37029029/104381193-d8c8bc00-550a-11eb-9acd-08c8f08c9c04.png)

What did I do wrong? What's the problem with the `Wiki` file?

**Comment by johann-lau** [comment]
try `pip install wiki` first

**Comment by edgui-appolonicorreia** [comment]
> try `pip install wiki` first

Thanks @johann-lau , and it worked well until when I needed the others requirements, like `api`, `page` and others!

So, I started to install all others dependencies:
![image](https://user-images.githubusercontent.com/37029029/105066451-9567d380-5a5d-11eb-98c9-54ddd1fac55b.png)
![image](https://user-images.githubusercontent.com/37029029/105066521-a57fb300-5a5d-11eb-8104-1e377ccb81c6.png)

But when I finally tried to import the `wikitools` I got this error message:
![image](https://user-images.githubusercontent.com/37029029/105066726-da8c0580-5a5d-11eb-97be-d8f040127130.png)

And there is not `category` lib:
![image](https://user-images.githubusercontent.com/37029029/105067117-29399f80-5a5e-11eb-8cc0-155e16b0cfca.png)

Any more tips? :)

**Comment by johann-lau** [comment]
I guess you may need to install category module from somewhere else. From my programming experience you shall be able to find it on pypi.org (however, I couldn’t find it there)

If this error persists, you may try using pip3 instead of pip. If it still happens, the best solution is to find an alternative to the module.
Hope that works @edgui-appolonicorreia :)

**Comment by edgui-appolonicorreia** [comment]
I found a alternative way hahahahahaha, using the method _read_html_ from pandas to scrap the SNPedia website.

Thanks anyway!
