### ISSUE TITLE
FileNotFound error when importing wikipedia

### ISSUE THREAD

**Issue by Jackaed** [goldsmith/Wikipedia#274]
I decided to make a quick and easy WikiRace bot, just as a fun project to tackle over my lunch break.

Attempting to do so led to this error:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\MY_ACCOUNT\\Documents\\PyCharm Files\\PyCharm Files\\Python\\lib\\site-packages\\certifi\\cacert.pem'

**Comment by willschlitzer** [comment]
@Jackaed Are you using a virtual environment? If so, is `wikipedia` listed when you type `pip list`?

**Comment by Jackaed** [comment]
Was digging through my old issues and found this one. Going to close as I no longer care.
