### ISSUE TITLE
[BUG] Some time not work

### ISSUE THREAD

**Issue by thedtvn** [goldsmith/Wikipedia#298]
![image](https://user-images.githubusercontent.com/80153297/140750084-80e95c6c-ec56-4fab-9786-a72608529dc7.png)
![image](https://user-images.githubusercontent.com/80153297/140750092-b42ab258-c1a6-4a62-9210-843cd0337c73.png)
**code in discord** 
```
@bot.command()
async def wiki(ctx,*, arg=None):

    def check(msg):
          return msg.author == ctx.author and msg.channel == ctx.channel
    embed=discord.Embed(title="Đang load")
    load = await ctx.send(embed=embed)
    x = wikipedia.search(arg, results=8)
    for count, item in enumerate(x, 1):
      t = f"{count} : {item}\n"
      n = f"{sup}{t}"
      tas(n)
    embed=discord.Embed(title="List tìm kiếm được", description=f"{sup}**Nhập một số ở trên để xem**")
    await load.edit(embed=embed)
    tas()
    msg = await bot.wait_for("message", timeout=60, check=check)
    s = int(msg.content) - 1
    url =  x[s]
    print(url)
    try:
      ny = wikipedia.page(str(url))
      text = ny.content
      text = text.split("\n\n\n")
      embed=discord.Embed(title=ny.title, url=ny.url, description=f"{text[0]}")
      await load.edit(embed=embed)
    except:
      embed=discord.Embed(title="404", description=f" Chúng tôi không thây trang bạn yêu cầu xin hoặc là NSFW thông cảm")
      await load.edit(embed=embed)`
```

**Comment by Violet-04** [comment]
It is most likely that the wrapper isn't the cause of your issue. Your `try` - `except` block literally handles all exceptions even though the errors may come from different places (e.g. `text[0]` exceeds Discord embed's limit).
Please be certain that your issue is related to the library before opening one.

**Comment by thedtvn** [comment]
> It is most likely that the wrapper isn't the cause of your issue. Your `try` - `except` block literally handles all exceptions even though the errors may come from different places (e.g. `text[0]` exceeds Discord embed's limit). Please be certain that your issue is related to the library before opening one.

Cảm ơn
