### ISSUE TITLE
GuessedAtParserWarning

### ISSUE THREAD

**Issue by thedtvn** [goldsmith/Wikipedia#301]
/opt/virtualenvs/python3/lib/python3.8/site-packages/wikipedia/wikipedia.py:389: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.  The code that caused this warning is on line 389 of the file /opt/virtualenvs/python3/lib/python3.8/site-packages/wikipedia/wikipedia.py. To get rid of this warning, pass the additional argument 'features="html5lib"' to the BeautifulSoup constructor.

**Comment by NirvashPrime** [comment]
This can be resolved by replacing line 389 of wikipedia.py with:
```lis = BeautifulSoup(html, 'html.parser').find_all('li')```

**Comment by Luen** [comment]
#107
